[versions]
android-gradle-plugin = "8.7.2"  # Asegúrate de que sea compatible con tu Android Studio

appcompat = "1.6.1"
material = "1.9.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
espresso = "3.5.1"
junit-version = "1.2.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
junit = { module = "junit:junit", version.ref = "junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
